### ISSUE TITLE
Error: Request failed with status code 403

### ISSUE THREAD

**Issue by ItsNiceCraft** [cronitorio/monitor-github-actions#40]
I'm trying to set up cronitor logging for a github actions workflow, but the Cronitor Monitoring Relay run fails with the following error:

```
** Cronitor for Github Actions **
Syncing workflow details to Cronitor
(node:1629) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Error: Request failed with status code 403
```

It appears like a request is being made to cronitor, as the telemetry API key was last used when the failed run happened.

**Comment by amalvivek** [comment]
Hey, are there any updates on this issue - experiencing the same thing.

**Comment by ItsNiceCraft** [comment]
I don't have one, sorry. Not much we can do about this rather than just wait

**Comment by shaneharter** [comment]
Sorry we missed this! This integration syncs job details so an "SDK" api key is necessary. The quickstart guide includes the suggested API key at the top so you can copy/paste it: 

https://cronitor.io/app/welcome/jobs/github
